name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      environment:
        description: name of environment
        required: true
      targetRef:
        description: target ref
        required: false
      skipFirstStep:
        description: Skip first step - only accepts 'yes' as valid value
        required: false

env:
  TARGET_REF: ${{ github.event.inputs.targetRef || github.ref }}

jobs:
  validate_inputs:
    runs-on: ubuntu-latest
    steps:
      # - name: Validate environment name
      #   if: ${{ !contains(fromJson('["dev", "prod"]'), env.ENV_NAME) }}
      #   run: |
      #     echo "${{ env.ENV_NAME }} is not a valid target environment for deployment"
      #     echo "$ENV_NAME is not a valid target environment for deployment"
      #     exit1
      - name: Validate environment name
        uses: actions/github-script@v4
        with:
          script: |
            const isValidEnvironment = ['dev', 'prod'].includes(context.payload.inputs.environment);
            console.log('isValidEnvironment', isValidEnvironment);
            if (!isValidEnvironment) {
              core.setFailed(`${context.payload.inputs.environment} is not a valid environment name for Property Estimating`); 
            }

            const isReleaseEnvironment = ['prod'].includes(context.payload.inputs.environment);

            if (isReleaseEnvironment && !context.payload.inputs.targetRef) {
              core.setFailed(`${context.payload.inputs.environment} needs to be specified git ref to deploy`);  
            }

      - name: Validate skipFirstStep
        if: ${{ github.event.inputs.skipFirstStep != '' && github.event.inputs.skipFirstStep != 'yes' }}
        run: |
          echo "${{ github.event.inputs.skipFirstStep }} is not a valid value for skipFirstStep."
          exit 1
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.TARGET_REF }}
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "github.ref ${{ github.ref }}!"
          echo "input.targetRef ${{ github.event.inputs.targetRef }}!"
          echo "env.TARGET_REF ${{ env.TARGET_REF }}!"
          echo "env.ENV_NAME ${{ env.ENV_NAME }}!"
          echo "env.ENV_NAME $ENV_NAME!"
          echo "github.event.inputs.skipFirstStep ${{ github.event.inputs.skipFirstStep }}"

  first_step:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}
      url: https://heathryu.com
    needs: validate_inputs
    if: ${{ github.event.inputs.skipFirstStep != 'yes' }}
    steps:
      - run: echo "Just running things in ref $TARGET_REF for environment ${{ github.event.inputs.environment }}"
