name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      environment:
        description: name of environment
        required: true
      targetRef:
        description: target ref
        required: false

env:
  TARGET_REF: ${{ github.event.inputs.targetRef || github.ref }}
  ENV_NAME: ${{ github.event.inputs.environment }}

jobs:
  say_hello:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate environment name
        if: ${{ !contains(['dev', 'prod'], env.ENV_NAME) }}
        run: |
          echo "$ENV_NAME is not a valid target environment for deployment"
          exit1
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.targetRef }}
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "github.ref ${{ github.ref }}!"
          echo "input.targetRef ${{ github.event.inputs.targetRef }}!"
          echo "env.TARGET_REF ${{ env.TARGET_REF }}!"
      
